language: go

services:
  - docker

before_install:                                                                 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
  - dep ensure
  
script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

after_success:
  - docker build -t mz47/lunchomat .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mz47/lunchomat
